import { link } from './affiliateLinks'

export const articles = [
  {
    id: 'best-12v-espresso-makers-boats',
    title: 'The Best 12V Espresso Makers for Boats',
    subtitle: 'Tested at Anchor off St. Aubin\'s Bay',
    silo: 'galley',
    siloLabel: 'The Galley',
    image: '/images/espresso.jpg',
    excerpt: 'A proper coffee at anchor is one of sailing\'s great pleasures. We\'ve rounded up the best compact espresso makers that actually work in a boat galley — no 12V required.',
    readTime: '8 min read',
    date: 'June 2026',
    body: [
      { type: 'p', text: 'There is a particular kind of smugness that comes from waking up anchored in a deserted cove, watching the tide come in across the flats, with a proper espresso in hand. For years, that meant a battered moka pot on a gas ring and a lot of patience. Not anymore.' },
      { type: 'p', text: 'The compact espresso maker market has matured considerably. There are now genuinely good options that produce real crema, weigh almost nothing, and won\'t fling grounds across the cabin when you hit a wake from a passing ferry. Here\'s what actually works.' },
      { type: 'callout', title: 'The Island Skipper\'s Test Conditions', text: 'These were tested aboard a 32ft sloop moored in St. Aubin\'s Bay and at anchor in Bonne Nuit Bay on Jersey\'s north coast. Morning temperatures 8–18°C. The porthole view in that photo is genuinely what you get.' },
      { type: 'h2', text: 'Our Top Picks' },
      { type: 'product', name: 'Wacaco Minipresso GR2', verdict: 'Best overall. Compact, genuinely excellent espresso, and hand-pumped — zero draw on the battery. A revelation on a boat. The one in our photos has done three seasons and shows no signs of stopping.', price: 'Around £55', link: link('wacaco-minipresso-gr2') },
      { type: 'product', name: 'Wacaco Picopresso', verdict: 'For the serious coffee sailor. Uses proper 58mm portafilter baskets — the same size as a real café machine. Produces outstanding espresso. Slightly bulkier but worth every millimetre.', price: 'Around £80', link: link('wacaco-picopresso') },
      { type: 'product', name: 'Handpresso Auto Capsule', verdict: 'The only one that plugs into a 12V socket. Uses Nespresso pods. Not as good as the Wacaco options but foolproof and tidy — good for less technical crew who just want to press a button.', price: 'Around £120', link: link('handpresso-auto-capsule') },
      { type: 'h2', text: 'What to Look For' },
      { type: 'p', text: 'The key specs: size (galley lockers are small), whether it needs power (every amp matters on a 12V system), and how much it moves around when the boat does. Manual pumped options like the Minipresso draw nothing from your battery, which is why they\'re our top recommendation for most sailors.' },
      { type: 'h2', text: 'The Island Skipper\'s Verdict' },
      { type: 'p', text: 'Buy the Wacaco Minipresso GR2. Unless you\'re very serious about your coffee — in which case step up to the Picopresso. Both produce espresso that would embarrass most high street cafés, require no power, and fit in the palm of your hand.' },
    ]
  },
  {
    id: 'best-boat-dehumidifiers-jersey',
    title: 'Best Boat Dehumidifiers 2026',
    subtitle: 'Jersey\'s Damp Problem, Solved',
    silo: 'cabin',
    siloLabel: 'The Cabin',
    image: '/images/dehumidifier.jpg',
    excerpt: 'Living aboard in the Channel Islands means fighting damp year-round. After testing six dehumidifiers in actual Jersey conditions — damp winters, misty mornings, 12m tidal swings — here\'s what genuinely works.',
    readTime: '10 min read',
    date: 'June 2026',
    body: [
      { type: 'p', text: 'If you keep a boat in Jersey, you know the damp problem. The Channel Islands sit in the Atlantic\'s flight path, the tidal range leaves boats drying out on mud twice a day, and even in summer the night air is thick with moisture. A good dehumidifier isn\'t a luxury here — it\'s basic boat maintenance.' },
      { type: 'p', text: 'I\'ve tested six units aboard over the past two seasons. Here\'s the honest verdict — and that photo shows exactly the setup that finally worked: EcoAir running in the saloon on a grey St. Helier Marina morning.' },
      { type: 'callout', title: 'The Jersey Context', text: 'Jersey\'s tidal range reaches 12 metres at springs. When the tide drops, the air fills with moisture from exposed mud and weed. Standard household dehumidifiers often can\'t cope below 15°C — you need something rated for real marine conditions.' },
      { type: 'h2', text: 'Top Picks' },
      { type: 'product', name: 'EcoAir DD1 Simple', verdict: 'Best all-round boat dehumidifier. Desiccant type — works effectively even in cold temperatures where compressor types struggle. Perfect for year-round use in the Channel Islands. The one in our photo.', price: 'Around £130', link: link('ecoair-dd1') },
      { type: 'product', name: 'Unibond Aero 360° Moisture Absorber', verdict: 'Best passive option. No power needed — runs on replaceable refills. Slower but silent and works 24/7. Ideal for boats left unattended. Keep two or three aboard at all times.', price: 'Around £12 + refills', link: link('unibond-aero-360') },
      { type: 'product', name: 'Meaco 10L Low Energy Dehumidifier', verdict: 'For liveaboards with shore power. Powerful, efficient, and quiet. Overkill for a weekend sailor but brilliant if you live aboard in St. Helier Marina full time.', price: 'Around £200', link: link('meaco-10l-dehumidifier') },
      { type: 'h2', text: 'Desiccant vs Compressor' },
      { type: 'p', text: 'This is the key decision for boat use. Compressor dehumidifiers lose effectiveness below 15°C. On a boat in Jersey between October and April, that\'s a serious problem. Desiccant types work right down to freezing and are almost always the better choice for Channel Islands boats.' },
    ]
  },
  {
    id: 'musto-vs-gill-vs-henri-lloyd-jacket',
    title: 'Musto vs Gill vs Henri Lloyd',
    subtitle: 'The Great Foul Weather Jacket Test',
    silo: 'deck',
    siloLabel: 'Deck & Dock',
    image: '/images/sailing-jacket.jpg',
    excerpt: 'Three iconic British sailing brands, three offshore jackets tested in Channel Islands conditions. One clear winner — and one surprise from the mid-price range.',
    readTime: '12 min read',
    date: 'May 2026',
    body: [
      { type: 'p', text: 'Every serious sailor eventually faces this decision. The three dominant British sailing clothing brands each make offshore-rated foul weather jackets in the £300–600 range. They all look good on a chandlery hanger. But how do they actually perform when you\'re on the helm at 0200, spray flying, with the French coast somewhere to port?' },
      { type: 'p', text: 'I wore each jacket for a full season passage — St. Helier to Cherbourg, the Race of Alderney, overnight to Dartmouth — before writing this. That photo is the Musto HPX on the backstay as we came into St. Peter Port. It was raining.' },
      { type: 'callout', title: 'Test Conditions', text: 'Channel Islands passages, May–September 2025. Conditions ranged from flat calm to Force 7 gusts on the Race of Alderney. All jackets tested at the helm and below, wet and dry, day and night.' },
      { type: 'h2', text: 'The Verdict' },
      { type: 'product', name: 'Musto HPX Gore-Tex Jacket', verdict: 'Best waterproofing. After four hours on the helm in breaking seas, the inside was bone dry. Gore-Tex Pro fabric, properly taped seams. The gold standard — and priced accordingly.', price: '£595', link: link('musto-hpx-jacket') },
      { type: 'product', name: 'Gill OS3 Coastal Jacket', verdict: 'The surprise winner on value. At £320 it\'s the cheapest of the three, but the fit is excellent, pockets perfectly placed, and it kept me dry in everything the Channel threw at it. Best all-rounder.', price: '£320', link: link('gill-os3-jacket') },
      { type: 'product', name: 'Henri Lloyd Fremantle Offshore', verdict: 'The one you\'ll want to wear into St. Helier for dinner after. Genuinely handsome, performs offshore, and the cut and finish is exceptional. Waterproofing slightly behind Musto but not by much.', price: '£450', link: link('henri-lloyd-fremantle') },
      { type: 'h2', text: 'The Island Skipper\'s Pick' },
      { type: 'p', text: 'If money is no object, the Musto HPX. If you want the best combination of performance and value, the Gill OS3 Coastal is genuinely hard to beat — and the £275 you save buys a lot of diesel.' },
    ]
  },
  {
    id: 'best-nesting-cookware-boats',
    title: 'Best Nesting Cookware for Boats',
    subtitle: 'Galley Tested, Galley Approved',
    silo: 'galley',
    siloLabel: 'The Galley',
    image: '/images/pots-and-pans.jpg',
    excerpt: 'Space is everything in a boat galley. The best nesting pan sets that actually cook well, store flat, and survive salt air — tested in a real Channel Islands galley.',
    readTime: '7 min read',
    date: 'May 2026',
    body: [
      { type: 'p', text: 'A boat galley is roughly the size of a broom cupboard, and you\'re expected to cook three meals a day in it, sometimes while the boat is heeled at 20 degrees. The photo above is our actual galley — that gimballed stove and the spice rack above it are aboard a 32ft sloop in St. Helier Marina. This isn\'t a studio set.' },
      { type: 'callout', title: 'Galley Reality', text: 'Most of the cooking on a Channel Islands passage happens in a seaway. Gimballed stoves help, but you still need pans that sit stably, heat evenly, and are light enough to handle one-handed when you need to grab a shroud.' },
      { type: 'h2', text: 'Top Picks' },
      { type: 'product', name: 'Sea to Summit Detour Stainless Steel Cookset', verdict: 'Best overall. Lightweight stainless, foldable handles, compact nest. Used this for three seasons — tough, easy to clean, and the lids double as plates. Perfect for two to four people aboard.', price: 'Around £85', link: link('sea-to-summit-cookset') },
      { type: 'product', name: 'Optimus Terra Weekend HE Cookset', verdict: 'Best heat efficiency. The hard-anodised aluminium heats incredibly fast on a single-burner gas stove — useful when you\'re watching the gas gauge on a long passage.', price: 'Around £65', link: link('optimus-terra-cookset') },
      { type: 'product', name: 'Magma Cookware Nesting 7-Piece Set', verdict: 'Best for larger boats. Proper stainless construction, stay-cool handles, dedicated storage pot. Expensive but a serious piece of kit for a serious galley.', price: 'Around £180', link: link('magma-cookware-7piece') },
      { type: 'h2', text: 'What to Avoid' },
      { type: 'p', text: 'Cheap non-stick coatings degrade fast in a salty, humid environment. Avoid anything where the non-stick is the main selling point — go stainless or hard-anodised aluminium. Also avoid sets where handles don\'t fold or detach; they\'re galley space killers.' },
    ]
  },
  {
    id: 'best-led-deck-lights-boats',
    title: 'Best LED Deck Lights for Boats',
    subtitle: 'Sundowners in Style',
    silo: 'cabin',
    siloLabel: 'The Cabin',
    image: '/images/led-deck-lights.jpg',
    excerpt: 'The right deck lighting transforms a boat at anchor. Our picks for every budget — including the ones that made that photograph possible.',
    readTime: '6 min read',
    date: 'April 2026',
    body: [
      { type: 'p', text: 'That photograph is not staged. That\'s a real evening anchored in St. Aubin\'s Bay, with St. Helier\'s lights on the horizon and a bottle of something cold on the table. The warm amber glow from under the cockpit coaming is an Osculati LED strip on a dimmer. This is what the right lighting does to a boat.' },
      { type: 'p', text: 'Good deck lighting does two things: makes the cockpit usable after dark without destroying your night vision, and makes the boat look beautiful at anchor. The key is warm white LEDs on a dimmer. Cool white makes a boat look like a hospital ward.' },
      { type: 'callout', title: 'St. Aubin\'s Bay at Anchor', text: 'Anchoring off St. Aubin\'s on a summer evening, with Elizabeth Castle lit up to the east — this is when good deck lighting earns its keep. These are the products that have made those evenings genuinely special.' },
      { type: 'h2', text: 'Top Picks' },
      { type: 'product', name: 'Osculati LED Strip Light with Dimmer', verdict: 'Best overall. Waterproof, warm 3000K white, dimmable, minimal current draw. Mount under the cockpit coaming for the perfect ambient glow. The one in our photos.', price: 'Around £35', link: link('osculati-led-strip') },
      { type: 'product', name: 'Lopolight 360° Anchor Light', verdict: 'The best anchor light on the market. Visible at range, tiny current draw, and clean Scandinavian design. A proper upgrade from a standard masthead fitting.', price: 'Around £95', link: link('lopolight-anchor-light') },
      { type: 'product', name: 'Lunasea Submersible Underwater Light', verdict: 'The indulgence pick. Fit one below the waterline and the whole anchorage glows blue-green. Purely aesthetic but genuinely magical on a still summer night.', price: 'Around £120', link: link('lunasea-underwater-light') },
    ]
  },
  {
    id: 'best-boat-shoes-2026',
    title: 'Best Boat Shoes 2026',
    subtitle: 'From Deck to St. Helier and Back',
    silo: 'deck',
    siloLabel: 'Deck & Dock',
    image: '/images/deck-shoes.jpg',
    excerpt: 'A good pair of deck shoes needs to grip wet fibreglass, look decent in a marina restaurant, and last more than one season. Tested on Jersey\'s notoriously slippery slipways.',
    readTime: '8 min read',
    date: 'April 2026',
    body: [
      { type: 'p', text: 'That photo was taken at Gorey Harbour with Mont Orgueil Castle in the background — and those shoes are sitting on wet, weedy granite at low tide. That\'s the real test. Any shoe that grips that surface grips everywhere.' },
      { type: 'callout', title: 'The Jersey Test', text: 'Grève de Lecq slipway at low tide is perhaps the most treacherous surface in the Channel Islands — wet, weedy granite at a steep angle. That\'s where these were tested. If they pass there, they pass everywhere.' },
      { type: 'h2', text: 'Top Picks' },
      { type: 'product', name: 'Sperry Top-Sider Gold Cup', verdict: 'The classic, still the best. Wave-siping on the outsole grips wet decks brilliantly, the leather upper is properly water-resistant, and they look right in any marina in the world.', price: 'Around £130', link: link('sperry-top-sider-gold-cup') },
      { type: 'product', name: 'Sebago Docksides', verdict: 'The European alternative to Sperry and arguably better made. Traditional construction, excellent sole grip, and they age beautifully. A staple of every Channel Islands marina.', price: 'Around £145', link: link('sebago-docksides') },
      { type: 'product', name: 'Musto Dynamic Pro II Sailing Shoe', verdict: 'Best for performance sailing. More technical than a classic deck shoe — designed for racing and offshore work. Exceptional grip and support when things get lively.', price: 'Around £115', link: link('musto-dynamic-pro-shoe') },
      { type: 'h2', text: 'After Dark: Après-Sail' },
      { type: 'p', text: 'The Sperry and Sebago options both work perfectly off the boat. With chinos and a Breton top for a post-sail dinner in St. Helier, they\'re exactly right. No need to change footwear unless you\'re going somewhere very smart.' },
    ]
  },
  {
    id: 'best-unbreakable-wine-glasses-boats',
    title: 'The Sundowner Kit',
    subtitle: 'Unbreakable Glasses & the Perfect Anchor Drink',
    silo: 'galley',
    siloLabel: 'The Galley',
    image: '/images/unbreakable-glasses.jpg',
    excerpt: 'That photograph — two glasses, golden hour, Elizabeth Castle in the distance — is what good kit makes possible. Here\'s everything you need for the perfect sundowner at anchor.',
    readTime: '6 min read',
    date: 'March 2026',
    body: [
      { type: 'p', text: 'That stern plate reads "The Island Skipper — Jersey" and those are two glasses of something cold with the sun going down behind Elizabeth Castle. This is the point of all of it. The right glass makes a difference — not for snobbish reasons, but because a proper wine glass shape affects how the wine tastes and how the evening feels.' },
      { type: 'p', text: 'The catch is that real glass on a boat is a hazard and a liability. The solution is polycarbonate — but not all polycarbonate glasses are equal. The bad ones look like picnic glasses. The good ones are indistinguishable from crystal at arm\'s length.' },
      { type: 'callout', title: 'That Photo', text: 'The glasses in the photograph are Sea to Summit Delta Wine Glasses. The stern nameplate is hand-engraved brass. Elizabeth Castle is visible over the port quarter as the sun sets behind it.' },
      { type: 'h2', text: 'The Glasses' },
      { type: 'product', name: 'Sea to Summit Delta Wine Glass', verdict: 'Best overall. Genuinely attractive polycarbonate that doesn\'t look like a camping cup. Stackable, dishwasher safe, and virtually indestructible. These are the ones in our photos.', price: 'Around £18 each', link: link('sea-to-summit-wine-glass') },
      { type: 'product', name: 'Govino Flexible Wine Glass', verdict: 'Best for rougher conditions. Flexible polycarbonate that won\'t crack if dropped on fibreglass. The go-to for passages and whenever things get lively.', price: 'Around £12 for 4', link: link('govino-wine-glass') },
      { type: 'product', name: 'Riedel Swirl Stemless', verdict: 'The indulgence pick — actual glass, but specifically engineered to be harder to knock over. For calm anchorages only. Worth the risk for a special evening.', price: 'Around £35 for 2', link: link('riedel-swirl-stemless') },
      { type: 'h2', text: 'Complete Sundowner Kit' },
      { type: 'p', text: 'Round out the kit with the Osculati LED deck lights (warm, dimmable, mounted under the coaming) and a Hydro Flask insulated bottle to keep the wine cold. The Channel Islands sunset does the rest.' },
    ]
  },
  {
    id: 'sailing-around-jersey-gear-guide',
    title: 'Sailing Around Jersey',
    subtitle: 'The Kit You Actually Need',
    silo: 'galley',
    siloLabel: 'The Galley',
    image: '/images/espresso.jpg',
    excerpt: 'A complete gear guide for Channel Islands sailing — written by someone who actually does it. From the Race of Alderney to drying out at Grève de Lecq.',
    readTime: '15 min read',
    date: 'March 2026',
    body: [
      { type: 'p', text: 'People ask what makes sailing around Jersey different. The answer is the tides. Everything here is about the tides. The Channel Islands sit at the confluence of the Atlantic and the English Channel, creating tidal flows that can run at 8 knots in the Race of Alderney. Get the timing wrong and you\'re going backwards. Get it right and you\'re flying.' },
      { type: 'callout', title: 'The Channel Islands Tidal Reality', text: 'Jersey\'s 12m tidal range is the second largest in the world. This affects everything: where you can anchor, what time you can enter and leave harbours, and what gear you need when the tide does something unexpected.' },
      { type: 'h2', text: 'The Galley on a Passage' },
      { type: 'p', text: 'For passages of 4–6 hours (St. Helier to Cherbourg, for example), provisioning is straightforward: a good thermos of hot soup, rolls, fruit, and plenty of water. The Wacaco Minipresso is worth its weight in coffee beans for the return leg.' },
      { type: 'product', name: 'Stanley Classic Vacuum Flask 1L', verdict: 'Best passage flask. Keeps hot for 24 hours genuinely — tested at anchor overnight in October. Tough enough to survive the kind of treatment a boat gives things.', price: 'Around £40', link: link('stanley-vacuum-flask') },
      { type: 'h2', text: 'The Dried-Out Experience' },
      { type: 'p', text: 'Drying out — leaving your boat to sit on the bottom at low water — is a normal part of sailing in Jersey. Grève de Lecq, St. Catherine\'s Bay, and parts of St. Aubin\'s Harbour all see boats dry out regularly at springs. You need a proper boarding ladder and the patience to wait for the tide.' },
      { type: 'product', name: 'Plastimo Telescopic Boarding Ladder', verdict: 'Essential if you ever dry out. A 4-step telescopic ladder that stores flat against the transom and deploys quickly. Non-negotiable for any boat sailing Jersey waters.', price: 'Around £85', link: link('plastimo-boarding-ladder') },
      { type: 'h2', text: 'The Island Hopping Kit List' },
      { type: 'list', items: ['Chartplotter + paper charts (both, always)', 'VHF radio — fixed AND handheld backup', 'Stanley flask + Wacaco Minipresso', 'Sea to Summit nesting cookware', 'Boarding ladder for drying-out', 'Musto or Gill foul weather gear', 'EcoAir dehumidifier for overnight stops'] },
    ]
  },
  {
    id: 'how-to-stop-boat-smelling-damp',
    title: 'How to Stop Your Boat Smelling Damp',
    subtitle: 'The Complete Guide',
    silo: 'cabin',
    siloLabel: 'The Cabin',
    image: '/images/dehumidifier.jpg',
    excerpt: 'The bilge smell is not inevitable. With the right combination of products and habits, a boat cabin can smell as fresh as a hotel room. Here\'s how.',
    readTime: '9 min read',
    date: 'February 2026',
    body: [
      { type: 'p', text: 'Every sailor knows the smell: the moment you open the hatch after a week away and get hit by that particular combination of diesel, damp, and something faintly biological. It doesn\'t have to be like this. With the right approach, a boat can smell genuinely pleasant.' },
      { type: 'callout', title: 'Why Jersey Boats Get Damp', text: 'The Channel Islands climate is mild but very moist — Atlantic air, frequent sea mist, and the dramatic tidal range all conspire to pump moisture into boat cabins. A boat left closed for a week in Jersey in October will be noticeably damper than the same boat in the Mediterranean.' },
      { type: 'h2', text: 'Step 1: Source Control' },
      { type: 'p', text: 'Before throwing dehumidifiers at the problem, find the moisture sources. Common culprits: leaking deck fittings, hatches that don\'t seal fully, wet foul weather gear stored below, and the bilge. Fix the leaks first — everything else is treating symptoms.' },
      { type: 'h2', text: 'Step 2: Active Dehumidification' },
      { type: 'product', name: 'EcoAir DD1 Simple Desiccant Dehumidifier', verdict: 'Our top pick for powered dehumidification. Run this for a few hours after each trip and the cabin transformation is remarkable. See the full dehumidifier review for detailed comparison.', price: 'Around £130', link: link('ecoair-dd1') },
      { type: 'h2', text: 'Step 3: Passive Absorbers' },
      { type: 'product', name: 'Unibond Aero 360° Moisture Absorber', verdict: 'Place one in the forward cabin, one aft, one in the main saloon. Refill every 4–6 weeks. Silent, cheap, works around the clock even when you\'re not aboard.', price: '£12 + refills', link: link('unibond-aero-360') },
      { type: 'h2', text: 'Step 4: Bedding' },
      { type: 'product', name: 'Spun Cloud Nautical Moisture-Wicking Bedding', verdict: 'Boat-specific bedding that wicks moisture away from the sleeping surface. Transforms the aft cabin from a damp sleeping bag experience into something genuinely comfortable.', price: 'Around £75 for a set', link: link('spun-cloud-bedding') },
      { type: 'h2', text: 'Step 5: Air Circulation' },
      { type: 'p', text: 'A 12V fan left running on low keeps air moving through the cabin and prevents the stagnant pockets where mould develops. Leave hatches cracked when possible — even a centimetre of airflow makes a significant difference.' },
    ]
  },
]

export function getArticle(id) {
  return articles.find(a => a.id === id)
}

export function getArticlesByCategory(silo) {
  return articles.filter(a => a.silo === silo)
}
